### ISSUE TITLE
Latest nginx-ee/nginx-common/nginx-custom ok with this script?

### ISSUE THREAD

**Issue by yyhmsg** [VirtuBox/nginx-ee#13]
First, thanks for this great script.  I have just a quick question about the latest easy engine downloads and your script to ensure they are all ok.

I noticed on my server today the following packages have apt updates:
  nginx-common nginx-custom nginx-ee

These are the underlying packages from easy engine as best I can tell (updated very recently) that your script updates.  Should these updates be installed? or should the easy engine packages be removed from apt when using your script? or some other option?  Eventually I will need to do a apt dist-upgrade for something and don't want to mess up our productive servers if these updates break the changes your script has made.

Please advise on the best course of action.  Thanks!

**Comment by VirtuBox** [comment]
Hello @yyhmsg, 

It's only a matter of choice, because the new nginx-ee release is up-to-date with Nginx v1.14.0, and the only differences with nginx-ee compiled with my bash script are the additional modules.
So, if you prefer to use the nginx-ee package available from the EasyEngine repository, you can install it to replace the compiled nginx.

You may have to make some changes in your nginx.conf because if you have used my nginx.conf example, there are some directives for additional modules not shipped with nginx-ee (rtCamp).

And you will have to use the following command to allow nginx package update (blocked by default in my script)  : 
```
sudo apt-mark unhold nginx-ee nginx-common
```
If you prefer to keep the compiled nginx, you still can update your packages with apt upgrade because nginx-ee and nginx-common are already marked as hold, and should not be replaced by nginx package from the apt repository.

**Comment by yyhmsg** [comment]
I'd rather keep your script as it is more likely to be kept up to date.  I see:

 apt-mark showhold
nginx-common
nginx-ee


Should nginx-custom also be held back?  or will that not matter?

**Comment by VirtuBox** [comment]
It doesn't matter, I have run `apt update && apt full-upgrade -y` on my servers running with EasyEngine and the compiled nginx isn't replaced by the new nginx-ee release from the apt repository.
