### ISSUE TITLE
Bloatware binary produced

### ISSUE THREAD

**Issue by dvershinin** [VirtuBox/nginx-ee#61]
The binary is not stripped of debugging symbols and instead of ~6M you end up with an ~14M NGINX binary.

More details [here](https://www.getpagespeed.com/server-setup/where-compilation-went-wrong) in my sort of blog post - bug report :)

**Comment by VirtuBox** [comment]
Hello @dvershinin,

thanks for your report, issue has been fixed with PR https://github.com/VirtuBox/nginx-ee/pull/62.

After reading your blog post, I think you haven't noticed two points about this script : 
- you have the choice to compile Nginx with the latest OpenSSL stable or dev release, but you can also compile Nginx with OpenSSL from system libraries (flag : `--openssl-system`)
- I already provide Nginx as [debian package](https://build.opensuse.org/package/show/home:virtubox:WordOps/nginx) and this script is only intended for users who want the last bleeding edge version of Nginx

Regards,
