### ISSUE TITLE
Change Nginx to Openresty as default Openresty Nginx

### ISSUE THREAD

**Issue by petrukngantuk** [VirtuBox/nginx-ee#78]
**Is your feature request related to a problem? Please describe.**
Yes, I have a nginx config that request to support lua, and want to integrate it with plesk for better and easy management...

**Describe the solution you'd like**
Is there a simple way to replace default nginx to openresty that support plesk?

I already research it, but always 403 forbidden,,, not sure what's problem there...

**Comment by VirtuBox** [comment]
Hello @petrukngantuk,
Sorry about my answer delay. 
I have not used openresty enough to know all the differences between OpenResty and Nginx. But if you have 403 forbidden issues, it's probably due to openresty user/group.
With Plesk it should be `nginx:nginx`, and it's better to set it before the compilation by adding `--user=nginx --group=nginx`  to the `./configure` command.
And nginx user should be added into psaserv group with `usermod -aG psaserv nginx`.
